env:
  browser: true
  es6: true
extends: airbnb
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
plugins:
  - react
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console: 0
  jsx-a11y/no-static-element-interactions: 0
